### ISSUE TITLE
Add typechecking for env variables

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/serlo-editor-as-lti-tool#100]
Similar to https://github.com/serlo/api.serlo.org/blob/staging/packages/server/src/env.d.ts

**Comment by elbotho** [comment]
we might even consider something like this if we want to get fancy :)
https://thomwright.co.uk/2022/02/01/validating-config/

(or [something like this ](https://github.com/t3-oss/t3-env) but it's using zod – like almost everybody else ^^)
