### ISSUE TITLE
Find a better way to implement saving of named version before tab is closed

### ISSUE THREAD

**Issue by kulla** [serlo/serlo-editor-as-lti-tool#104]
In https://github.com/serlo/ece-as-a-service/blob/2f2b55af6a90dd0bd5850a1e44116423c4dc84d3/src/frontend/editor.tsx#L137-L183 we use a deprecated method to save a named version. Thus we need a better solution.

Ideas:

* use the local storage to save the document -> In case a save couldn't be done we can use this store to restore the document when it is opened the next time
* use a web worker for saving the document (they live in a background thread and might be longer open)

**Comment by LarsTheGlidingSquirrel** [comment]
There is no confirmation any more. We will look for a solution on the editor package level. Closed for now.
