### ISSUE TITLE
refactor: remove url-join

### ISSUE THREAD

**Issue by elbotho** [serlo/serlo-editor-as-lti-tool#115]
url-join is not really needed any more.

>**You might not need this library**
This library was originally created before the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL_API) was standardized and widely available in popular runtimes such as browsers and Node.js. Depending on your use-case you might want to consider using the standardized API over this library.
(from https://github.com/jfromaniello/url-join)

Especially since there was a problem with the newest version of url-join we should probably just use the URL API instead.

**Comment by LarsTheGlidingSquirrel** [comment]
I was using `new URL(url, base)` before. However, sadly it is not just concatenating what you give it. Example: 
```typescript
console.log(new URL('test', 'https://example.com/i-get-replaced').href) // https://example.com/test
console.log(new URL('test', 'https://example.com/i-wont-get-replaced/').href) // https://example.com/i-wont-get-replaced/test
```
We could try to remember to always put a `/` at the end. But I prefer a small helper function more.

**Comment by elbotho** [comment]
Okay, then we'll keep it for now. Thanks for the explanation.
